const crypto = require("crypto");
const { cmd } = require("../command");

cmd({
  pattern: "gpass",
  desc: "Generate a strong password.",
  category: "other",
  react: '🔐',
  filename: __filename
}, async (message, client, args, { reply }) => {
  try {
    // Get password length from arguments or default to 12
    const length = args[0] ? parseInt(args[0]) : 12;
    
    // Validate length
    if (isNaN(length) || length < 8) {
      return reply("Please provide a valid length for the password (Minimum 8 characters).");
    }

    // Password generation function
    const generatePassword = (len) => {
      const chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+[]{}|;:,.<>?";
      let password = '';
      
      for (let i = 0; i < len; i++) {
        const randomIndex = crypto.randomInt(0, chars.length);
        password += chars[randomIndex];
      }
      
      return password;
    };

    // Generate the password
    const password = generatePassword(length);

    // Send the password message with newsletter context
    await message.sendMessage(
      message.chat, 
      {
        text: `🔐 *Your Strong Password* 🔐\n\n` +
              `Password length: ${length} characters\n\n` +
              `Generated by *Silva Spark MD*`
      },
      {
        quoted: message,
        contextInfo: {
          forwardingScore: 5,
          isForwarded: true,
          forwardedNewsletterMessageInfo: {
            newsletterJid: '120363302677217436@newsletter',
            newsletterName: "CASEYRHODES-XMD",
            serverMessageId: 143
          }
        }
      }
    );

    // Send the actual password in a separate message
    await message.sendMessage(
      message.chat, 
      { text: password },
      { quoted: message }
    );

  } catch (error) {
    console.error("Password generation error:", error);
    reply("❌ Error generating password: " + error.message);
  }
});
